<a href="https://colab.research.google.com/github/codeRisshi25/Statistical_Machine_Learning_Assignments/blob/main/STMlab_asgn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SECTION 1 NUMPY**

1. Import numpy as np and check its version

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.26.4


2. Write a script to create a 1D array with >= 15 items and print the even numbers.

In [ ]:
arr = np.arange(0,20,1)
print ([x for x in arr if x%2==0])

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


3. Write a script to find the mean of all the elements in a 1D array.

In [ ]:
print (arr.mean())

9.5


4. Write a script to create a Boolean array where values are False if the element is an even
number.

In [ ]:
print (arr%2!=0)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]


5. Write a script in numpy to reshape an array and convert a 1D array to 2D array.

In [ ]:
print(arr.reshape(2,-2))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


6. Write a script to stack two arrays vertically.

In [ ]:
arr1 = np.arange(0,5,1)
arr2 = np.arange(6,11,1)
print(np.vstack((arr1,arr2)))

[[ 0  1  2  3  4]
 [ 6  7  8  9 10]]


7. Write a script to extract the second row from a 2D array.

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1])


[4 5 6]


8. Write a script to add 1 to each element in a 2D array.

In [ ]:
print(arr2d + 1)

9. Write a script to perform matrix multiplication between two 2D array

In [ ]:
arr3 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(np.dot(arr2d, arr3))

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


10. Write a script to remove items from one array that are present in another array.

In [ ]:
arr4 = np.array([1, 2, 3, 4, 5])
arr5 = np.array([3, 5])
print(np.setdiff1d(arr4, arr5))

[1 2 4]


11. Write a script to find the positions where elements of two arrays match

In [ ]:
arr6 = np.array([1, 2, 3, 4, 5])
arr7 = np.array([3, 1, 5])
print(np.where(np.in1d(arr6, arr7))[0])

[0 2 4]


12. Import a dataset using numpy keeping the text intact and print the first three rows.

In [ ]:
from numpy import genfromtxt
data = genfromtxt('log.csv', delimiter=',', dtype=None, encoding=None)
print(data[:3])

[['id' 'title' 'author' 'format' 'price']
 ['1' '"The Adventures of Duck and Goose"' '"Sir Quackalot"' 'paperback'
  '10.99']
 ['2' '"The Return of Duck and Goose"' '"Sir Quackalot"' 'paperback'
  '19.99']]


**SECTION 2 PANDAS**

1.Write a script that reads a csv file from a specified source and print the first 10 rows
using the pandas package.

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv');
print (df.head(10))

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39


2.Write a script to select a particular series from Diamonds Dataframe. Print the content of
the series.

In [ ]:
print (df['cut'])

0            Ideal
1          Premium
2             Good
3          Premium
4             Good
           ...    
53935        Ideal
53936         Good
53937    Very Good
53938      Premium
53939        Ideal
Name: cut, Length: 53940, dtype: object


3. Create a new series ‘Quality-merge’ by combining any two columns of the DataFrame

In [ ]:
df['Quality-merge'] = df['cut'] + ', ' + df['color']
print(df['Quality-merge'])

0            Ideal, E
1          Premium, E
2             Good, E
3          Premium, I
4             Good, J
             ...     
53935        Ideal, D
53936         Good, D
53937    Very Good, D
53938      Premium, H
53939        Ideal, D
Name: Quality-merge, Length: 53940, dtype: object


4. Write a script to determine the number of rows and columns with the datatypes of each
column in the diamonds DataFrame.

In [ ]:
print(df.shape)
print(df.dtypes)

(53940, 11)
carat            float64
cut               object
color             object
clarity           object
depth            float64
table            float64
price              int64
x                float64
y                float64
z                float64
Quality-merge     object
dtype: object


5. Write a script to summarize only the diamonds DataFrame ‘object’ column.

In [ ]:
# prompt: select the column with datatype object and describe it

print(df.describe(include=object))


          cut  color clarity Quality-merge
count   53940  53940   53940         53940
unique      5      7       8            35
top     Ideal      G     SI1      Ideal, G
freq    21551  11292   13065          4884


6. Write a script to count the number of missing values in each Series of diamonds
Dataframe.

In [ ]:
print(df.isnull().sum())

carat            0
cut              0
color            0
clarity          0
depth            0
table            0
price            0
x                0
y                0
z                0
Quality-merge    0
dtype: int64


7. Write a script to drop a row if any or all values in a row are missing from diamonds
Dataframe on two specific columns.

In [ ]:
df = df.dropna(subset=['cut', 'color'])
print(df)


       carat        cut color clarity  depth  table  price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

      Quality-merge  
0          Ideal,